### ISSUE TITLE
Not saving settings

### ISSUE THREAD

**Issue by suotroel** [ferion11/PeaZip_Appimage#1]
All these PeaZip appimages (including the last one, 8.9) don't save the settings anywhere when you change them and try to save them.

**Comment by ferion11** [comment]
Thanks for the report.
I think it's because i'm using the portable version (that maybe is saving the setting on the tmp directory). I will need to test the Appimage with the normal version.

**Comment by ferion11** [comment]
Fixed in the last version:
https://github.com/ferion11/PeaZip_Appimage/releases
